# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "payroll": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://GreciaMendoza.github.io/nbdev_Grema/"

git_url = "https://github.com/GreciaMendoza/nbdev_Grema/tree/master/"

def custom_doc_links(name): return None
