# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'payroll']

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# Cell
def payroll():
  name = input("Enter the name of the employee: ==> ")
  hours = int(input("Enter the number of hours worked by the employeer ==> "))
  rate = float(input("Enter the pay rate for one hour ==> "))

  total_money = hours * rate
  print("The total money earned by ", name, "for working ", hours, "hours", "is ===> ", round(total_money), "CAD")